topograp2/Ewha-market

app.py, static/css/purchase.css, static/css/purchase_list.css, templates/purchase.html, templates/purchase_list.html
> ex) FE (html, css)
> 상품 구매 화면, 판매자 관점 구매 페이지 구현
=> purchase, purchase_list 페이지 제작

templates/index.html
> ex) FE, BE
FE
list.html에서 필요없는 a 태그 삭제
=> update:index.html 필요없는 코드 삭제

app.py, static/reg_items.js, templates/reg_items.html
> ex) FE, BE
FE
위와 같이 major category 변경 시 detail category가 변경되도록 구현했습니다.
=> feat: 상품 등록화면에서 major category에 따라 detail category 변경되는 기능 구현

static/signup.js
> ex) FE, BE
FE
회원가입 페이지에서 아이디 / 비밀번호 칸이 공백인 상태에서 오른쪽 확인 버튼을 누를 경우, 사용자에게 공백 상태임을 알리는 메시지를 하단에 추가하였습니다. 
코드 수정하고 보니, input 태그에  required를 추가해서 공백인 상태인 경우를 폼 제출 시에 알려주고 방지해주긴 하더라고요 😁 그래도 일단은 없는 것보단 나으니 수정해서 올렸습니다.
=> update: 회원가입 페이지에서 아이디/비밀번호 공백 상태에서 확인 버튼 누르는 경우 안내메시지 추가

static/reg_reviews.js, templates/reg_reviews.html
> ex) FE, BE
FE
상품 상세에서 리뷰 등록 버튼을 눌러서 리뷰 등록 페이지로 이동 시에 별점을 누르면 별점 svg가 깨지는 현상을 해결했습니다.
=> fix : 상품 상세에서 리뷰 등록 버튼 눌렀을 때 이미지 깨짐 해결

app.py, database.py, templates/profile_edit.html
> BE
> 프로필 편집 email/tel 입력란에 보이는 기본값을 사용자의 기존 email/tel로 수정
=> 프로필 편집 email/tel 기본값

static/css/profile_edit.css, static/profile_edit.js, templates/profile_edit.html
> ex) FE, BE
FE
프로필 편집 페이지에서 특수문자, 영문, 숫자가 포함된 비밀번호 / 확인한 비밀번호만 폼에 제출할 수 있게 구현했습니다.
=> update: 프로필 편집 비밀번호 유효성 검사 구현

database.py, static/profile_edit.js
> ex) FE, BE
BE
회원이 좋아요한 아이템이 없는 경우에 noneType으로  database.py에서 처리를 해줘서 에러가 발생했는데,
noneType을 빈 딕셔너리로 반환해서 처리해주었습니다.
=> fix: 좋아요한 아이템이 없는 경우에 마이페이지 처리

app.py, templates/my_page.html
> ex) FE, BE
FE, BE
app.py에서 my_page에 해당되는 부분에 아이디로 이메일과 tel 찾는 함수 넣었고
email, tel data를 html에서 나타나도록 수정했습니다.
=> fix : 마이페이지에서 유저에 해당하는 email, tel 나오게 수정

app.py, database.py, templates/index.html, templates/search_results.html
> ex) FE, BE
BE
Search바에서 아이템 이름 검색 시 아이템 나오게 수정했습니다.
* searchbar css 수정
* search_results.html 구성 변경 및 각 아이템 페이지로 이동하게 만들기
* search_results.css 
세 가지가 필요할 것 같은데 일단은 제가 searchbar css 오늘 중으로 해놓겠습니다.
=> feat : item search 구현

static/css/style.css
> ex) FE, BE
FE
로그인 하면 전체적인 메뉴가 이상하게 변해서 searchbar width 작게해서 수정했습니다. 😅
=> style:로그인 시  searchbar 확인 후 수정

app.py, database.py, templates/list.html, templates/my_page.html, templates/product_detail.html, templates/purchase.html
> ex) BE (관련 FE 조금)
> purchase 관련된 기능 구현했습니다 -- db의 'order' 항목에 주문사항 정리, 동적 연결 및 기능 구현 완료
마이페이지 로딩 중 유저 정보 하나하나 가져오지 않고 유저 자체를 불러와서 이메일, 전화번호 받도록 함수 단일화했습니다
> css 템플릿에 맞게 수정해주시면서 js 이용해서 '회원 정보와 같음' 누르면 플레이스홀더 정보들이 실제 값으로 전달되도록 정리해주셔야 할 것 같습니다
=> 'order' DB define, purchase 기능 구현

app.py, database.py, static/reg_items.js, templates/list.html, templates/reg_items.html, templates/review.html
> ex) BE
> item DB에서 한국어로 나오지 않던 값들을 한국어로 수정해두었습니다
리뷰 리스트에서도 상품 카테고리별 리뷰를 확인할 수 있게 수정했습니다
=> ReviewList categorized / DB value >> ENG to KOR

static/css/style.css, templates/index.html
> ex) FE, BE
FE
리뷰등록 버튼을 누를 시 searchbar 안의 input과 button이 기존의 위치에 있지 않고 flex-direction: column으로 나타나는 현상을 수정했습니다.
=> style: 리뷰등록 시 searchbar css 수정

static/css/style.css, static/main.js, templates/index.html
> ex) FE, BE
FE
index.html에서 상단 메뉴 선택 시에 bold + white 되어야 하는데 안 되는 현상을 jinja2 템플릿 이용해서 해결했습니다. 
=> fix: 상단 메뉴 선택 시 색 변경

static/css/product_detail.css, templates/product_detail.html
=> 상품 상세 페이지 수정

templates/login.html
> ex) FE, BE
FE
로그인 페이지 비밀번호 찾기 삭제
=> update: 로그인 페이지 비밀번호 찾기 삭제

static/css/product_detail.css
> ex) FE
> purchase_detail에서 컨테이너가 중앙으로 설정되도록 수정함
=> purchase_detail css 수정

static/css/list.css, static/css/review.css, templates/reg_items.html
=> reg_items 상품설명 placeholder 수정

database.py
=> 아이디 중복 재수정

static/css/product_detail.css, templates/product_detail.html
=> 좋아요 기능 구현 수정
